
[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = true

[net]
tickrate = 60
port = 1212
bindto = "::,0.0.0.0"
pvs = false

[status]
enabled = true
bind = "*:1212"

[game]
savefile = "world.yml"
saveinterval = 60

[console]
width = 120
height = 60
password = "operationbloodyhellm8"
hostpassword = "operationbloodyhellm8"
loginlocal = true

[build]
engine_version = "0.2.9"
fork_id = "kdc_paint"
version = "2012250"
download_url = "https://20kdc.duckdns.org/kdc_paint_5.zip"
hash = ""

